// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/RedisLabs/provider-rediscloud/apis/rediscloud/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Database.
func (mg *Database) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.SubscriptionID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SubscriptionIDRef,
		Selector:     mg.Spec.ForProvider.SubscriptionIDSelector,
		To: reference.To{
			List:    &v1alpha1.SubscriptionList{},
			Managed: &v1alpha1.Subscription{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubscriptionID")
	}
	mg.Spec.ForProvider.SubscriptionID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubscriptionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.SubscriptionID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.SubscriptionIDRef,
		Selector:     mg.Spec.InitProvider.SubscriptionIDSelector,
		To: reference.To{
			List:    &v1alpha1.SubscriptionList{},
			Managed: &v1alpha1.Subscription{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubscriptionID")
	}
	mg.Spec.InitProvider.SubscriptionID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubscriptionIDRef = rsp.ResolvedReference

	return nil
}
