// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ActivePrivateServiceConnectInitParameters struct {

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type ActivePrivateServiceConnectObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription
	// The ID of the Private Service Connect
	PrivateServiceConnectServiceID *float64 `json:"privateServiceConnectServiceId,omitempty" tf:"private_service_connect_service_id,omitempty"`

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type ActivePrivateServiceConnectParameters struct {

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	// +kubebuilder:validation:Optional
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	// +kubebuilder:validation:Optional
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

// ActivePrivateServiceConnectSpec defines the desired state of ActivePrivateServiceConnect
type ActivePrivateServiceConnectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ActivePrivateServiceConnectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ActivePrivateServiceConnectInitParameters `json:"initProvider,omitempty"`
}

// ActivePrivateServiceConnectStatus defines the observed state of ActivePrivateServiceConnect.
type ActivePrivateServiceConnectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ActivePrivateServiceConnectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ActivePrivateServiceConnect is the Schema for the ActivePrivateServiceConnects API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rediscloud}
type ActivePrivateServiceConnect struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionId) || (has(self.initProvider) && has(self.initProvider.regionId))",message="spec.forProvider.regionId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subscriptionId) || (has(self.initProvider) && has(self.initProvider.subscriptionId))",message="spec.forProvider.subscriptionId is a required parameter"
	Spec   ActivePrivateServiceConnectSpec   `json:"spec"`
	Status ActivePrivateServiceConnectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ActivePrivateServiceConnectList contains a list of ActivePrivateServiceConnects
type ActivePrivateServiceConnectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ActivePrivateServiceConnect `json:"items"`
}

// Repository type metadata.
var (
	ActivePrivateServiceConnect_Kind             = "ActivePrivateServiceConnect"
	ActivePrivateServiceConnect_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ActivePrivateServiceConnect_Kind}.String()
	ActivePrivateServiceConnect_KindAPIVersion   = ActivePrivateServiceConnect_Kind + "." + CRDGroupVersion.String()
	ActivePrivateServiceConnect_GroupVersionKind = CRDGroupVersion.WithKind(ActivePrivateServiceConnect_Kind)
)

func init() {
	SchemeBuilder.Register(&ActivePrivateServiceConnect{}, &ActivePrivateServiceConnectList{})
}
