// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ActivePrivateServiceConnectEndpointAccepterInitParameters struct {

	// Accept or reject the endpoint (accepted values are accept and reject)
	// Accept or reject the endpoint
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect Endpoint
	PrivateServiceConnectEndpointID *float64 `json:"privateServiceConnectEndpointId,omitempty" tf:"private_service_connect_endpoint_id,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect
	PrivateServiceConnectServiceID *float64 `json:"privateServiceConnectServiceId,omitempty" tf:"private_service_connect_service_id,omitempty"`

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type ActivePrivateServiceConnectEndpointAccepterObservation struct {

	// Accept or reject the endpoint (accepted values are accept and reject)
	// Accept or reject the endpoint
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect Endpoint
	PrivateServiceConnectEndpointID *float64 `json:"privateServiceConnectEndpointId,omitempty" tf:"private_service_connect_endpoint_id,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect
	PrivateServiceConnectServiceID *float64 `json:"privateServiceConnectServiceId,omitempty" tf:"private_service_connect_service_id,omitempty"`

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

type ActivePrivateServiceConnectEndpointAccepterParameters struct {

	// Accept or reject the endpoint (accepted values are accept and reject)
	// Accept or reject the endpoint
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect Endpoint
	// +kubebuilder:validation:Optional
	PrivateServiceConnectEndpointID *float64 `json:"privateServiceConnectEndpointId,omitempty" tf:"private_service_connect_endpoint_id,omitempty"`

	// The ID of the Private Service Connect Service relative to the associated subscription Modifying this attribute will force creation of a new resource.
	// The ID of the Private Service Connect
	// +kubebuilder:validation:Optional
	PrivateServiceConnectServiceID *float64 `json:"privateServiceConnectServiceId,omitempty" tf:"private_service_connect_service_id,omitempty"`

	// The ID of the region, as created by the API Modifying this attribute will force creation of a new resource.
	// The ID of the GCP region
	// +kubebuilder:validation:Optional
	RegionID *float64 `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The ID of the Pro subscription to attach Modifying this attribute will force creation of a new resource.
	// The ID of the Pro subscription to attach
	// +kubebuilder:validation:Optional
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`
}

// ActivePrivateServiceConnectEndpointAccepterSpec defines the desired state of ActivePrivateServiceConnectEndpointAccepter
type ActivePrivateServiceConnectEndpointAccepterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ActivePrivateServiceConnectEndpointAccepterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ActivePrivateServiceConnectEndpointAccepterInitParameters `json:"initProvider,omitempty"`
}

// ActivePrivateServiceConnectEndpointAccepterStatus defines the observed state of ActivePrivateServiceConnectEndpointAccepter.
type ActivePrivateServiceConnectEndpointAccepterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ActivePrivateServiceConnectEndpointAccepterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ActivePrivateServiceConnectEndpointAccepter is the Schema for the ActivePrivateServiceConnectEndpointAccepters API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rediscloud}
type ActivePrivateServiceConnectEndpointAccepter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.action) || (has(self.initProvider) && has(self.initProvider.action))",message="spec.forProvider.action is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privateServiceConnectEndpointId) || (has(self.initProvider) && has(self.initProvider.privateServiceConnectEndpointId))",message="spec.forProvider.privateServiceConnectEndpointId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.privateServiceConnectServiceId) || (has(self.initProvider) && has(self.initProvider.privateServiceConnectServiceId))",message="spec.forProvider.privateServiceConnectServiceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionId) || (has(self.initProvider) && has(self.initProvider.regionId))",message="spec.forProvider.regionId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subscriptionId) || (has(self.initProvider) && has(self.initProvider.subscriptionId))",message="spec.forProvider.subscriptionId is a required parameter"
	Spec   ActivePrivateServiceConnectEndpointAccepterSpec   `json:"spec"`
	Status ActivePrivateServiceConnectEndpointAccepterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ActivePrivateServiceConnectEndpointAccepterList contains a list of ActivePrivateServiceConnectEndpointAccepters
type ActivePrivateServiceConnectEndpointAccepterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ActivePrivateServiceConnectEndpointAccepter `json:"items"`
}

// Repository type metadata.
var (
	ActivePrivateServiceConnectEndpointAccepter_Kind             = "ActivePrivateServiceConnectEndpointAccepter"
	ActivePrivateServiceConnectEndpointAccepter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ActivePrivateServiceConnectEndpointAccepter_Kind}.String()
	ActivePrivateServiceConnectEndpointAccepter_KindAPIVersion   = ActivePrivateServiceConnectEndpointAccepter_Kind + "." + CRDGroupVersion.String()
	ActivePrivateServiceConnectEndpointAccepter_GroupVersionKind = CRDGroupVersion.WithKind(ActivePrivateServiceConnectEndpointAccepter_Kind)
)

func init() {
	SchemeBuilder.Register(&ActivePrivateServiceConnectEndpointAccepter{}, &ActivePrivateServiceConnectEndpointAccepterList{})
}
