// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ActivePrivateServiceConnect) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActivePrivateServiceConnectEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActivePrivateServiceConnectEndpointAccepter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActiveSubscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActiveSubscriptionDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActiveSubscriptionPeering) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActiveSubscriptionRegions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ActiveTransitGatewayAttachment) Hub() {}
