// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DatabaseInitParameters struct {

	// ID of the database to which the Rule should apply.
	// The database (id)
	Database *float64 `json:"database,omitempty" tf:"database,omitempty"`

	// For databases in Active/Active subscriptions only, the regions to which the Rule should apply.
	// For ActiveActive databases only
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// ID of the subscription containing the database.
	// The subscription (id) to which the database belongs
	Subscription *float64 `json:"subscription,omitempty" tf:"subscription,omitempty"`
}

type DatabaseObservation struct {

	// ID of the database to which the Rule should apply.
	// The database (id)
	Database *float64 `json:"database,omitempty" tf:"database,omitempty"`

	// For databases in Active/Active subscriptions only, the regions to which the Rule should apply.
	// For ActiveActive databases only
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// ID of the subscription containing the database.
	// The subscription (id) to which the database belongs
	Subscription *float64 `json:"subscription,omitempty" tf:"subscription,omitempty"`
}

type DatabaseParameters struct {

	// ID of the database to which the Rule should apply.
	// The database (id)
	// +kubebuilder:validation:Optional
	Database *float64 `json:"database" tf:"database,omitempty"`

	// For databases in Active/Active subscriptions only, the regions to which the Rule should apply.
	// For ActiveActive databases only
	// +kubebuilder:validation:Optional
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// ID of the subscription containing the database.
	// The subscription (id) to which the database belongs
	// +kubebuilder:validation:Optional
	Subscription *float64 `json:"subscription" tf:"subscription,omitempty"`
}

type RoleInitParameters struct {

	// A meaningful name for the role. Must be unique.
	// A meaningful name to identify the role, must be unique
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of rule association objects, documented below.
	// A set of rules which apply to the role
	Rule []RuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type RoleObservation struct {

	// Identifier of the Role created.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A meaningful name for the role. Must be unique.
	// A meaningful name to identify the role, must be unique
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of rule association objects, documented below.
	// A set of rules which apply to the role
	Rule []RuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`
}

type RoleParameters struct {

	// A meaningful name for the role. Must be unique.
	// A meaningful name to identify the role, must be unique
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of rule association objects, documented below.
	// A set of rules which apply to the role
	// +kubebuilder:validation:Optional
	Rule []RuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type RuleInitParameters struct {

	// a set of database association objects, documented below.
	// A set of databases to whom this rule applies within the role
	Database []DatabaseInitParameters `json:"database,omitempty" tf:"database,omitempty"`

	// Name of the Rule.
	// The name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleObservation struct {

	// a set of database association objects, documented below.
	// A set of databases to whom this rule applies within the role
	Database []DatabaseObservation `json:"database,omitempty" tf:"database,omitempty"`

	// Name of the Rule.
	// The name of the rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleParameters struct {

	// a set of database association objects, documented below.
	// A set of databases to whom this rule applies within the role
	// +kubebuilder:validation:Optional
	Database []DatabaseParameters `json:"database" tf:"database,omitempty"`

	// Name of the Rule.
	// The name of the rule
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

// RoleSpec defines the desired state of Role
type RoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleInitParameters `json:"initProvider,omitempty"`
}

// RoleStatus defines the observed state of Role.
type RoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Role is the Schema for the Roles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rediscloud}
type Role struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || (has(self.initProvider) && has(self.initProvider.rule))",message="spec.forProvider.rule is a required parameter"
	Spec   RoleSpec   `json:"spec"`
	Status RoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleList contains a list of Roles
type RoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Role `json:"items"`
}

// Repository type metadata.
var (
	Role_Kind             = "Role"
	Role_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Role_Kind}.String()
	Role_KindAPIVersion   = Role_Kind + "." + CRDGroupVersion.String()
	Role_GroupVersionKind = CRDGroupVersion.WithKind(Role_Kind)
)

func init() {
	SchemeBuilder.Register(&Role{}, &RoleList{})
}
