//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentsInitParameters) DeepCopyInto(out *ServiceAttachmentsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentsInitParameters.
func (in *ServiceAttachmentsInitParameters) DeepCopy() *ServiceAttachmentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentsObservation) DeepCopyInto(out *ServiceAttachmentsObservation) {
	*out = *in
	if in.DNSRecord != nil {
		in, out := &in.DNSRecord, &out.DNSRecord
		*out = new(string)
		**out = **in
	}
	if in.ForwardingRuleName != nil {
		in, out := &in.ForwardingRuleName, &out.ForwardingRuleName
		*out = new(string)
		**out = **in
	}
	if in.IPAddressName != nil {
		in, out := &in.IPAddressName, &out.IPAddressName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentsObservation.
func (in *ServiceAttachmentsObservation) DeepCopy() *ServiceAttachmentsObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentsParameters) DeepCopyInto(out *ServiceAttachmentsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentsParameters.
func (in *ServiceAttachmentsParameters) DeepCopy() *ServiceAttachmentsParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnect) DeepCopyInto(out *ServiceConnect) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnect.
func (in *ServiceConnect) DeepCopy() *ServiceConnect {
	if in == nil {
		return nil
	}
	out := new(ServiceConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnect) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpoint) DeepCopyInto(out *ServiceConnectEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpoint.
func (in *ServiceConnectEndpoint) DeepCopy() *ServiceConnectEndpoint {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnectEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepter) DeepCopyInto(out *ServiceConnectEndpointAccepter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepter.
func (in *ServiceConnectEndpointAccepter) DeepCopy() *ServiceConnectEndpointAccepter {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnectEndpointAccepter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterInitParameters) DeepCopyInto(out *ServiceConnectEndpointAccepterInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectEndpointID != nil {
		in, out := &in.PrivateServiceConnectEndpointID, &out.PrivateServiceConnectEndpointID
		*out = new(float64)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterInitParameters.
func (in *ServiceConnectEndpointAccepterInitParameters) DeepCopy() *ServiceConnectEndpointAccepterInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterList) DeepCopyInto(out *ServiceConnectEndpointAccepterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceConnectEndpointAccepter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterList.
func (in *ServiceConnectEndpointAccepterList) DeepCopy() *ServiceConnectEndpointAccepterList {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnectEndpointAccepterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterObservation) DeepCopyInto(out *ServiceConnectEndpointAccepterObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectEndpointID != nil {
		in, out := &in.PrivateServiceConnectEndpointID, &out.PrivateServiceConnectEndpointID
		*out = new(float64)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterObservation.
func (in *ServiceConnectEndpointAccepterObservation) DeepCopy() *ServiceConnectEndpointAccepterObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterParameters) DeepCopyInto(out *ServiceConnectEndpointAccepterParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectEndpointID != nil {
		in, out := &in.PrivateServiceConnectEndpointID, &out.PrivateServiceConnectEndpointID
		*out = new(float64)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterParameters.
func (in *ServiceConnectEndpointAccepterParameters) DeepCopy() *ServiceConnectEndpointAccepterParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterSpec) DeepCopyInto(out *ServiceConnectEndpointAccepterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterSpec.
func (in *ServiceConnectEndpointAccepterSpec) DeepCopy() *ServiceConnectEndpointAccepterSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointAccepterStatus) DeepCopyInto(out *ServiceConnectEndpointAccepterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointAccepterStatus.
func (in *ServiceConnectEndpointAccepterStatus) DeepCopy() *ServiceConnectEndpointAccepterStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointAccepterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointInitParameters) DeepCopyInto(out *ServiceConnectEndpointInitParameters) {
	*out = *in
	if in.EndpointConnectionName != nil {
		in, out := &in.EndpointConnectionName, &out.EndpointConnectionName
		*out = new(string)
		**out = **in
	}
	if in.GCPProjectID != nil {
		in, out := &in.GCPProjectID, &out.GCPProjectID
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCName != nil {
		in, out := &in.GCPVPCName, &out.GCPVPCName
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCSubnetName != nil {
		in, out := &in.GCPVPCSubnetName, &out.GCPVPCSubnetName
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointInitParameters.
func (in *ServiceConnectEndpointInitParameters) DeepCopy() *ServiceConnectEndpointInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointList) DeepCopyInto(out *ServiceConnectEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceConnectEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointList.
func (in *ServiceConnectEndpointList) DeepCopy() *ServiceConnectEndpointList {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnectEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointObservation) DeepCopyInto(out *ServiceConnectEndpointObservation) {
	*out = *in
	if in.EndpointConnectionName != nil {
		in, out := &in.EndpointConnectionName, &out.EndpointConnectionName
		*out = new(string)
		**out = **in
	}
	if in.GCPProjectID != nil {
		in, out := &in.GCPProjectID, &out.GCPProjectID
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCName != nil {
		in, out := &in.GCPVPCName, &out.GCPVPCName
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCSubnetName != nil {
		in, out := &in.GCPVPCSubnetName, &out.GCPVPCSubnetName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectEndpointID != nil {
		in, out := &in.PrivateServiceConnectEndpointID, &out.PrivateServiceConnectEndpointID
		*out = new(float64)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.ServiceAttachments != nil {
		in, out := &in.ServiceAttachments, &out.ServiceAttachments
		*out = make([]ServiceAttachmentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointObservation.
func (in *ServiceConnectEndpointObservation) DeepCopy() *ServiceConnectEndpointObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointParameters) DeepCopyInto(out *ServiceConnectEndpointParameters) {
	*out = *in
	if in.EndpointConnectionName != nil {
		in, out := &in.EndpointConnectionName, &out.EndpointConnectionName
		*out = new(string)
		**out = **in
	}
	if in.GCPProjectID != nil {
		in, out := &in.GCPProjectID, &out.GCPProjectID
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCName != nil {
		in, out := &in.GCPVPCName, &out.GCPVPCName
		*out = new(string)
		**out = **in
	}
	if in.GCPVPCSubnetName != nil {
		in, out := &in.GCPVPCSubnetName, &out.GCPVPCSubnetName
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointParameters.
func (in *ServiceConnectEndpointParameters) DeepCopy() *ServiceConnectEndpointParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointSpec) DeepCopyInto(out *ServiceConnectEndpointSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointSpec.
func (in *ServiceConnectEndpointSpec) DeepCopy() *ServiceConnectEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectEndpointStatus) DeepCopyInto(out *ServiceConnectEndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectEndpointStatus.
func (in *ServiceConnectEndpointStatus) DeepCopy() *ServiceConnectEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectInitParameters) DeepCopyInto(out *ServiceConnectInitParameters) {
	*out = *in
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectInitParameters.
func (in *ServiceConnectInitParameters) DeepCopy() *ServiceConnectInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectList) DeepCopyInto(out *ServiceConnectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceConnect, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectList.
func (in *ServiceConnectList) DeepCopy() *ServiceConnectList {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceConnectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectObservation) DeepCopyInto(out *ServiceConnectObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivateServiceConnectServiceID != nil {
		in, out := &in.PrivateServiceConnectServiceID, &out.PrivateServiceConnectServiceID
		*out = new(float64)
		**out = **in
	}
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectObservation.
func (in *ServiceConnectObservation) DeepCopy() *ServiceConnectObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectParameters) DeepCopyInto(out *ServiceConnectParameters) {
	*out = *in
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectParameters.
func (in *ServiceConnectParameters) DeepCopy() *ServiceConnectParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectSpec) DeepCopyInto(out *ServiceConnectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectSpec.
func (in *ServiceConnectSpec) DeepCopy() *ServiceConnectSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectStatus) DeepCopyInto(out *ServiceConnectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectStatus.
func (in *ServiceConnectStatus) DeepCopy() *ServiceConnectStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectStatus)
	in.DeepCopyInto(out)
	return out
}
